const actionTypesExample = {
	LOAD_SUCCESS_EXAMPLE: 'LOAD_SUCCESS_EXAMPLE',
	LOAD_FAILURE_EXAMPLE: 'LOAD_FAILURE_EXAMPLE',
	LOADING_EXAMPLE: 'LOADING_EXAMPLE'
  }
  
  export default actionTypesExample
  